version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    #    image: project_django_production_postgres
    image: postgres:13.3-alpine
    container_name: postgres4
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=555
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: project_django_local_django
    container_name: django
    environment:
      - DB_HOST=localhost
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=555
    depends_on:
      - db
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    #    command: /start
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /start'



