# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: found_signal_params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='found_signal_params.proto',
  package='TraceRemoteNotifying',
  syntax='proto2',
  serialized_pb=_b('\n\x19\x66ound_signal_params.proto\x12\x14TraceRemoteNotifying\"\x8c\x06\n\x11\x46oundSignalParams\x12\x18\n\x10protocol_version\x18\x01 \x02(\x03\x12\x1b\n\x13\x63\x65nter_frequency_hz\x18\x02 \x02(\x03\x12\x14\n\x0c\x62\x61ndwidth_hz\x18\x03 \x02(\x03\x12\x16\n\x0e\x64\x65tection_time\x18\x04 \x01(\t\x12\x13\n\x0bsystem_name\x18\x05 \x01(\t\x12\x12\n\x06\x64\x65v_id\x18\x06 \x01(\x05:\x02-1\x12\x15\n\tsystem_id\x18\x07 \x01(\x05:\x02-1\x12\x15\n\rmodulation_id\x18\x08 \x01(\x05\x12\x18\n\x10systems_modes_id\x18\t \x01(\x05\x12\x16\n\nnetwork_id\x18\n \x01(\x05:\x02-1\x12\x18\n\x10system_mode_name\x18\x0b \x01(\t\x12\x17\n\x0fsymbol_rate_bod\x18\x0c \x01(\x01\x12\x16\n\x0estart_time_sec\x18\r \x01(\x01\x12\x14\n\x0c\x65nd_time_sec\x18\x0e \x01(\x01\x12\x16\n\x0e\x61verage_snr_db\x18\x0f \x01(\x01\x12\x12\n\nduty_cycle\x18\x10 \x01(\x01\x12\x1d\n\x15min_packet_period_sec\x18\x11 \x01(\x01\x12\x15\n\ris_continuous\x18\x12 \x01(\x08\x12\x1b\n\x13identification_prob\x18\x13 \x01(\x01\x12\x1d\n\x15is_spectrum_inversion\x18\x14 \x01(\x08\x12\x16\n\x0e\x63omment_string\x18\x15 \x01(\t\x12\x42\n\x08location\x18\x16 \x01(\x0b\x32\x30.TraceRemoteNotifying.FoundSignalParams.Location\x12\x19\n\rid_foreign_db\x18\x17 \x01(\x05:\x02-1\x1a\x92\x01\n\x08Location\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x1e\n\x16\x61rea_sector_start_grad\x18\x04 \x01(\x01\x12\x1c\n\x14\x61rea_sector_end_grad\x18\x05 \x01(\x01\x12\x15\n\rarea_radius_m\x18\x06 \x01(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FOUNDSIGNALPARAMS_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='TraceRemoteNotifying.FoundSignalParams.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TraceRemoteNotifying.FoundSignalParams.Location.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='TraceRemoteNotifying.FoundSignalParams.Location.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='TraceRemoteNotifying.FoundSignalParams.Location.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area_sector_start_grad', full_name='TraceRemoteNotifying.FoundSignalParams.Location.area_sector_start_grad', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area_sector_end_grad', full_name='TraceRemoteNotifying.FoundSignalParams.Location.area_sector_end_grad', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area_radius_m', full_name='TraceRemoteNotifying.FoundSignalParams.Location.area_radius_m', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=832,
)

_FOUNDSIGNALPARAMS = _descriptor.Descriptor(
  name='FoundSignalParams',
  full_name='TraceRemoteNotifying.FoundSignalParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='TraceRemoteNotifying.FoundSignalParams.protocol_version', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='center_frequency_hz', full_name='TraceRemoteNotifying.FoundSignalParams.center_frequency_hz', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bandwidth_hz', full_name='TraceRemoteNotifying.FoundSignalParams.bandwidth_hz', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detection_time', full_name='TraceRemoteNotifying.FoundSignalParams.detection_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_name', full_name='TraceRemoteNotifying.FoundSignalParams.system_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dev_id', full_name='TraceRemoteNotifying.FoundSignalParams.dev_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_id', full_name='TraceRemoteNotifying.FoundSignalParams.system_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modulation_id', full_name='TraceRemoteNotifying.FoundSignalParams.modulation_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='systems_modes_id', full_name='TraceRemoteNotifying.FoundSignalParams.systems_modes_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='network_id', full_name='TraceRemoteNotifying.FoundSignalParams.network_id', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_mode_name', full_name='TraceRemoteNotifying.FoundSignalParams.system_mode_name', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_rate_bod', full_name='TraceRemoteNotifying.FoundSignalParams.symbol_rate_bod', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time_sec', full_name='TraceRemoteNotifying.FoundSignalParams.start_time_sec', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time_sec', full_name='TraceRemoteNotifying.FoundSignalParams.end_time_sec', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='average_snr_db', full_name='TraceRemoteNotifying.FoundSignalParams.average_snr_db', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duty_cycle', full_name='TraceRemoteNotifying.FoundSignalParams.duty_cycle', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_packet_period_sec', full_name='TraceRemoteNotifying.FoundSignalParams.min_packet_period_sec', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_continuous', full_name='TraceRemoteNotifying.FoundSignalParams.is_continuous', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identification_prob', full_name='TraceRemoteNotifying.FoundSignalParams.identification_prob', index=18,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_spectrum_inversion', full_name='TraceRemoteNotifying.FoundSignalParams.is_spectrum_inversion', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment_string', full_name='TraceRemoteNotifying.FoundSignalParams.comment_string', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='TraceRemoteNotifying.FoundSignalParams.location', index=21,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_foreign_db', full_name='TraceRemoteNotifying.FoundSignalParams.id_foreign_db', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FOUNDSIGNALPARAMS_LOCATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=832,
)

_FOUNDSIGNALPARAMS_LOCATION.containing_type = _FOUNDSIGNALPARAMS
_FOUNDSIGNALPARAMS.fields_by_name['location'].message_type = _FOUNDSIGNALPARAMS_LOCATION
DESCRIPTOR.message_types_by_name['FoundSignalParams'] = _FOUNDSIGNALPARAMS

FoundSignalParams = _reflection.GeneratedProtocolMessageType('FoundSignalParams', (_message.Message,), dict(

  Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
    DESCRIPTOR = _FOUNDSIGNALPARAMS_LOCATION,
    __module__ = 'found_signal_params_pb2'
    # @@protoc_insertion_point(class_scope:TraceRemoteNotifying.FoundSignalParams.Location)
    ))
  ,
  DESCRIPTOR = _FOUNDSIGNALPARAMS,
  __module__ = 'found_signal_params_pb2'
  # @@protoc_insertion_point(class_scope:TraceRemoteNotifying.FoundSignalParams)
  ))
_sym_db.RegisterMessage(FoundSignalParams)
_sym_db.RegisterMessage(FoundSignalParams.Location)


# @@protoc_insertion_point(module_scope)
