# Generated by Django 3.2.7 on 2021-09-13 07:57

from django.db import migrations, models
import geo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApemsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strizh_name', models.CharField(default='стриж 0 (по умолчанию)', error_messages={'required': ''}, max_length=500, verbose_name='Имя стрижа')),
                ('freq_podavitelya', geo.models.IntegerRangeField(default=2400, error_messages={'required': ''}, verbose_name='Частота подавителя')),
                ('deg_podavitelya', geo.models.IntegerRangeField(default=60, error_messages={'required': ''}, verbose_name='Номер подавителя (60, 120 ...)')),
                ('type_podavitelya', models.CharField(choices=[('АПЕМ (Многоканальный)', 'АПЕМ (Многоканальный)'), ('Тестовый модуль', 'Тестовый модуль'), ('Шелест', 'Шелест'), ('Шелест (Многоканальный)', 'Шелест (Многоканальный)'), ('BarGen (Enter Morph)', 'BarGen (Enter Morph)'), ('BarGen (Плата Б)', 'BarGen (Плата Б)')], error_messages={'required': ''}, max_length=500, verbose_name='Тип подавителя')),
                ('ip_podavitelya', models.GenericIPAddressField(default='192.168.2.121', error_messages={'required': ''}, verbose_name='IP-адрес подавителя')),
                ('canal_podavitelya', geo.models.IntegerRangeField(default=0, error_messages={'required': ''}, verbose_name='Канал подавителя')),
                ('usileniye_db', geo.models.IntegerRangeField(default=0, error_messages={'required': ''}, verbose_name='Усиление')),
            ],
            options={
                'verbose_name': 'Конфигурация АПЕМ',
                'verbose_name_plural': 'АПЕМы',
                'ordering': ['-freq_podavitelya'],
            },
        ),
        migrations.CreateModel(
            name='DroneJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=500, verbose_name='Имя дрона')),
                ('center_freq', models.FloatField(verbose_name='Несущая частота')),
                ('brandwidth', models.FloatField(verbose_name='Пропускная способность')),
                ('detection_time', models.CharField(max_length=500, verbose_name='Время обнаружения')),
                ('comment_string', models.CharField(max_length=500, verbose_name='Комментарии')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('azimuth', models.CharField(max_length=500, verbose_name='Азимут')),
                ('area_sector_start_grad', models.FloatField(verbose_name='Внутренний радиус сектора')),
                ('area_sector_end_grad', models.FloatField(verbose_name='Внешний радиус сектора')),
                ('area_radius_m', models.FloatField(verbose_name='Радиус сектора (м)')),
                ('ip', models.CharField(max_length=500, verbose_name='IP-адрес стрижа')),
                ('current_time', models.CharField(default='', max_length=500, verbose_name='Время засечки')),
                ('strig_name', models.CharField(default='', max_length=500, verbose_name='Имя стрижа')),
            ],
            options={
                'verbose_name': 'Дрон',
                'verbose_name_plural': 'Дроны',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=500, verbose_name='Имя дрона')),
                ('center_freq', models.FloatField(verbose_name='Несущая частота')),
                ('brandwidth', models.FloatField(verbose_name='Пропускная способность')),
                ('detection_time', models.CharField(max_length=500, verbose_name='Время обнаружения')),
                ('comment_string', models.CharField(max_length=500, verbose_name='Комментарии')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('azimuth', models.CharField(max_length=500, verbose_name='Азимут')),
                ('area_sector_start_grad', models.FloatField(verbose_name='Внутренний радиус сектора')),
                ('area_sector_end_grad', models.FloatField(verbose_name='Внешний радиус сектора')),
                ('area_radius_m', models.FloatField(verbose_name='Радиус сектора (м)')),
                ('ip', models.CharField(max_length=500, verbose_name='IP-адрес стрижа')),
                ('current_time', models.CharField(default='', max_length=500, verbose_name='Время засечки')),
                ('strig_name', models.CharField(default='', max_length=500, verbose_name='Имя стрижа')),
            ],
            options={
                'verbose_name': 'Дрон',
                'verbose_name_plural': 'Дроны',
            },
        ),
        migrations.CreateModel(
            name='Strizh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='стриж 0 (по умолчанию)', max_length=500, verbose_name='Имя стрижа')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('ip1', models.CharField(default='', max_length=500, verbose_name='IP-адрес стрижа (хост 1)')),
                ('ip2', models.CharField(default='', max_length=500, verbose_name='IP-адрес стрижа (хост 2)')),
                ('uniping_ip', models.CharField(default='', max_length=500, verbose_name='IP-адрес Uniping')),
                ('radius', models.FloatField(blank=True, default=500, null=True, verbose_name='Радиус')),
            ],
            options={
                'verbose_name': 'Стриж',
                'verbose_name_plural': 'Стрижи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrizhJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered_strizhes', models.CharField(default='стриж 0 (по умолчанию)', max_length=500, verbose_name='Нужные стрижи')),
                ('start_datetime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время начала')),
                ('end_datetime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время конца')),
            ],
            options={
                'verbose_name': 'Отфильтрованные стрижи',
                'ordering': ['-pk'],
            },
        ),
    ]
