# Generated by Django 3.2.4 on 2021-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apemsconfiguration',
            name='strizh_name',
            field=models.CharField(default='стриж 0 (по умолчанию)', max_length=500, verbose_name='Имя стрижа'),
        ),
    ]
