# Generated by Django 3.2.4 on 2021-08-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_apemsconfiguration_strizh_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apemsconfiguration',
            name='strizh_name',
            field=models.CharField(choices=[('стриж 1. АСБ', 'стриж 1. АСБ'), ('стриж 2 (СКЛАД)', 'стриж 2 (СКЛАД)')], max_length=500, verbose_name='Имя стрижа'),
        ),
    ]
